#!/usr/bin/env awesome-bash

awesome_shell_help <<_HELP_

Checks and installs dependencies for webservice-check project

Usage: $awesome_shell_script_name

_HELP_
#awesome-shell ref:6764e68

awesome_shell_include system

install_pip(){
    url="https://bootstrap.pypa.io/get-pip.py"
    silent_exec_with_title "Downloading get-pip.py" curl -O "$url"
    fatal_if_any_error "Cannot download $url"
    verbose_exec sudo -H python get-pip.py
    fatal_if_any_error "Cannot install pip"
    rm get-pip.py
}

install_pip_package(){
    sudo -H pip install --install-option '--install-data=/usr/local' "$*"
}

msg "Pip installation requires super user privileges"
awesome_shell_include password
keep_sudo_alive
silent_exec_with_title "Check if pip is installed" has_command pip || install_pip

packages=(nose requests)
for package in "${packages[@]}"
do
    silent_exec_with_title "Install $package" install_pip_package "$package"
done
